### ISSUE TITLE
Indicate ferries

### ISSUE THREAD

**Issue by pietervdvn** [anyways-open/functional-routeplanner-ovl#11]
The client asked that, if the cycleroute takes a ferry, this is clearly indicated in the UI

**Comment by xivk** [comment]
Example route: https://www.fietsrouteplanner.org/#map=15.45/3.74385/51.11071&route=bicycle.commute,Langerbrugsestraat%20245%2C%209940%20Evergem/3.73658/51.11313,Langerbruggestraat%2C%209000%20Ghent%2C%20Belgium/3.74835/51.10973
