### ISSUE TITLE
[Routing] Vreemde routering aan technologiepark

### ISSUE THREAD

**Issue by xivk** [anyways-open/functional-routeplanner-ovl#15]
Deze geeft een voorkeursroute die heel vreemd lijkt:

https://www.fietsrouteplanner.org/#map=16.52/3.70432/51.01046&route=bicycle.commute,Grotesteenweg-Noord%201%2C%209052%20Gent/3.70099/51.00877,Bollebergen%205%2C%209052%20Gent/3.70502/51.01251

**Comment by pietervdvn** [comment]
What does the path say?
Zuid-Oostelijk "fietspad" staat aangeduid als pad, noord-westelijke als volwaardig fietspad.

![image](https://user-images.githubusercontent.com/1466478/147354935-34ba92b9-698f-49e3-ac5e-558bf476a184.png)

**Comment by pietervdvn** [comment]
UPdated in OSM
