### ISSUE TITLE
Visualising cycleway=track which makes part of an existing way

### ISSUE THREAD

**Issue by Thierry1030** [anyways-open/functional-routeplanner-ovl#7]
highway=cycleway and cycleway=lane are also visualised -> good thing! 👍️
As you know, cycleways are not always mapped 'separately' but also as part of an already existing way.
So I think it's a good idea to include these cycleways as well -> example: https://www.openstreetmap.org/way/225920657#map=16/51.3317/4.9218

**Comment by xivk** [comment]
I don't think we should visualize this tag. It basically says 'there is a separate cycle lane' so that should be mapped separately.
