### ISSUE TITLE
Add redirect from 'fietsrouteplanner.org' to 'www.fietsrouteplanner.org'

### ISSUE THREAD

**Issue by pietervdvn** [anyways-open/functional-routeplanner-ovl#9]
Going to [https://fietsrouteplanner.org](https://fietsrouteplanner.org) directly (without www) gives the NGINX welcome screen.

**Comment by xivk** [comment]
Fixed in https://github.com/anyways-open/deployment/commit/bd0c311942f0c58b702ab98504bdb4741da5413b and https://github.com/anyways-open/deployment/commit/aad1e98367843edda151f88c06bcaa02878e92cb
